# Generated by Django 4.0.5 on 2022-06-18 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesave',
            name='image_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_post.imagestore'),
        ),
        migrations.AlterField(
            model_name='imagesave',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
