# Generated by Django 4.0.5 on 2022-06-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_post', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagestore',
            name='like_count',
        ),
    ]
