# Generated by Django 4.0.5 on 2022-06-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('confirm_password', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('profile_image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('is_active', models.BooleanField()),
                ('is_block', models.BooleanField()),
                ('is_admin', models.BooleanField()),
                ('rejection_count', models.IntegerField()),
            ],
        ),
    ]
