# Generated by Django 4.0.5 on 2022-06-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_remove_user_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('Afghanistan', 'Afghanistan'), ('Brazil', 'Brazil'), ('Australia', 'Australia'), ('Canada', 'Canada'), ('France', 'France'), ('Colombia', 'Colombia'), ('Germany', 'Germany'), ('Indonesia', 'Indonesia'), ('Italy', 'Italy'), ('Japan', 'Japan')], max_length=30),
        ),
    ]
