# Generated by Django 4.0.5 on 2022-06-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='trending_status',
        ),
        migrations.AddField(
            model_name='topic',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
