# Generated by Django 4.0.5 on 2022-06-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_followpeople'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followpeople',
            old_name='follow_user_id',
            new_name='follow_user',
        ),
    ]
